# config/cloudinary.yml
development:
  cloud_name: "dqlqmfjkt"
  api_key: "933439148883485"
  api_secret: "dlXWVq3P_mof5Int6b5JumM-_V4"

production:
  cloud_name: "dqlqmfjkt"
  api_key: "933439148883485"
  api_secret: "dlXWVq3P_mof5Int6b5JumM-_V4"